#!/usr/bin/env bash
# Brings up the lab's replica: one replica for all six canisters, so the
# four games and the book can be driven from one page.
#
# Deliberately WITHOUT --clean. A game canister's resolver is its threshold
# key, and on a local replica that key is derived from the canister id. Wiping
# the replica while escrows are alive on devnet destroys the only key that can
# ever settle or cancel them: the money then waits for refund() and the
# deadline, and nothing else can free it. So this script reuses the replica if
# it is already running, and only deploys what is missing.
#
# A wipe still happens by accident — a machine crash took the replica's state
# once already. That case is recoverable, because a local replica hands out
# canister ids strictly in order: recreate the same canisters in the same
# order and the ids, and with them the threshold keys and the resolvers, come
# back identical. `pad1..pad4` in dfx.json exist only for that: on this shared
# local replica four ids were already taken (by an earlier project) before the
# lab's own canisters were created, so the pads burn those four ids and keep
# the sequence aligned. They are created, never installed.
#
# The check below is the point: if an id drifts from the one recorded in
# .dfx/local/canister-ids.expected, the resolver is a different key and every
# live escrow is stranded until refund. The script says so instead of quietly
# carrying on.
#
# Usage: scripts/lab-up.sh            — bring up / top up
#        WIPE=1 scripts/lab-up.sh     — start over (only when no escrow lives)
set -euo pipefail
cd "$(dirname "$0")/.."

SOL_RPC_URL=${SOL_RPC_URL:-https://api.devnet.solana.com}
INDEX=${INDEX:-$(cd ../Crown-Index && pwd)}
RELAY=${RELAY:-$(cd ../Crown-Relay && pwd)}
GAMES=${GAMES:-$(cd ../crown-games && pwd)}
AR_WASM32=${AR_WASM32:-$(command -v llvm-ar || ls -d "$HOME"/.cache/solana/*/platform-tools/llvm/bin/llvm-ar 2>/dev/null | sort -V | tail -1 | grep . || echo "$HOME/.cache/zig/zig-ar")}

value() { grep "^$1" "config/testnet.toml" | head -1 | cut -d'=' -f2- | tr -d ' "'; }
SPLITTER=$(value splitter)
USDC=$(value usdc)
FACTORIES="$(value factory_two_outcome)\", \"$(value factory_stream)"

echo "== crown-index: local profile (the replica's own sol_rpc has no Default sources)"
# No cursor seed: Crown-Index does not poll — the book is filled by paid pushes
# through crown-relay (the smoke runs and the page's donate flow do the pushing).
cat > "$INDEX/config/local.toml" <<EOF
# Generated by Crown-Lab/scripts/lab-up.sh; never committed.
ingest_price  = 10_000_000_000
min_gross     = 1
attach_cycles = 10_000_000_000
cycle_floor   = 1_000_000_000
max_attributions = 1

[[chain]]
id        = "solana-devnet"
source    = "Custom:$SOL_RPC_URL"
consensus = "equality"
splitter  = "$SPLITTER"
usdc      = "$USDC"
factories = ["$FACTORIES"]
EOF

echo "== auction: local profile (its read side goes through the replica's sol_rpc)"
# The auction is the sighted game: register_entry reads the escrow through the
# SOL RPC canister, and the replica's own sol_rpc knows no Default sources —
# so its profile swaps the source for the Custom devnet URL.
sed -e "s|^source.*|source    = \"Custom:$SOL_RPC_URL\"|" \
    -e "s|^consensus.*|consensus = \"equality\"|" \
    "$GAMES/Auction/config/testnet.toml" > "$GAMES/Auction/config/local.toml"

echo "== build the wasms"
(cd "$INDEX" && CROWN_PROFILE=local \
    CC_wasm32_unknown_unknown="$INDEX/scripts/wasm-cc.sh" \
    AR_wasm32_unknown_unknown="$AR_WASM32" \
    cargo build --target wasm32-unknown-unknown --release -p crown-index)
# The relayer is pure Rust — no C, no local profile (index/allowlist via override).
(cd "$RELAY" && cargo build --target wasm32-unknown-unknown --release -p crown-relay)
for game in Conditional-Tasks:conditional-tasks Conditional-Funding:conditional-funding Subscription:subscription; do
    dir=${game%%:*}; package=${game##*:}
    (cd "$GAMES/$dir" && cargo build --target wasm32-unknown-unknown --release -p "$package")
done
(cd "$GAMES/Auction" && CROWN_PROFILE=local \
    CC_wasm32_unknown_unknown="$GAMES/Auction/scripts/wasm-cc.sh" \
    AR_wasm32_unknown_unknown="$AR_WASM32" \
    cargo build --target wasm32-unknown-unknown --release -p auction)

# The replica must survive this script: never pipe `dfx start --background`
# (the daemon inherits the pipe and the command hangs forever), and never run
# it from a background job whose process group later gets killed.
if ! dfx ping >/dev/null 2>&1; then
    echo "== start the replica"
    [ "${WIPE:-0}" = "1" ] && rm -rf .dfx
    setsid dfx start --background </dev/null >lab-replica.log 2>&1
    for _ in $(seq 1 60); do dfx ping >/dev/null 2>&1 && break; sleep 1; done
    dfx ping >/dev/null 2>&1 || { echo "FAIL: replica never answered"; exit 1; }
else
    echo "== replica already running (resolvers of live escrows preserved)"
fi

deployed() { dfx canister id "$1" >/dev/null 2>&1; }
# `dfx canister id` answers from canister_ids.json even when the replica no
# longer holds the canister, so existence is asked of the replica itself.
alive() { dfx canister status "$1" >/dev/null 2>&1; }

# Recovery: the ids are recorded but the replica lost them (a wipe or a crash).
# Burn the same four ids first, or everything below lands on shifted ids.
if deployed conditional-tasks && ! alive conditional-tasks; then
    echo "== replica lost its canisters; reproducing the id sequence"
    for pad in pad1 pad2 pad3 pad4; do
        alive "$pad" || dfx canister create "$pad" >/dev/null 2>&1 || true
    done
fi

echo "== canisters"
deployed sol_rpc || dfx deploy sol_rpc
if ! deployed crown-index; then
    dfx deploy crown-index --argument "(opt record {
        sol_rpc = opt principal \"$(dfx canister id sol_rpc)\" })"
else
    # A live crown-index is UPGRADED so its book persists: it is derived, but it
    # accumulates across runs and the games weigh votes by it. Migrating a
    # replica that still holds the OLD polling crown-index is a one-time manual
    # reinstall (its stable layout differs) — after that this upgrade keeps the
    # book. crown-index holds no keys.
    dfx canister install crown-index --mode upgrade --yes \
        --wasm "$INDEX/target/wasm32-unknown-unknown/release/crown_index.wasm" \
        >/dev/null 2>&1 || echo "WARN: crown-index upgrade failed — migrating from the old crown-index? reinstall once"
fi
INDEX_ID=$(dfx canister id crown-index)

# A live game canister gets the freshly built wasm (mode upgrade keeps its
# stable state and its threshold key: the key depends only on the id).
upgrade_if_alive() {
    local name=$1 wasm=$2
    if deployed "$name" && alive "$name"; then
        dfx canister install "$name" --mode upgrade --wasm "$wasm" --yes \
            || echo "WARN: upgrade of $name failed (это стоит прочитать)"
    fi
}

deployed conditional-tasks || dfx deploy conditional-tasks --argument "(opt record {
    crown_index = opt principal \"$INDEX_ID\" })"
upgrade_if_alive conditional-tasks "$GAMES/Conditional-Tasks/target/wasm32-unknown-unknown/release/conditional_tasks.wasm"
deployed conditional-funding || dfx deploy conditional-funding --argument "(opt record {
    crown_index = opt principal \"$INDEX_ID\" })"
upgrade_if_alive conditional-funding "$GAMES/Conditional-Funding/target/wasm32-unknown-unknown/release/conditional_funding.wasm"
deployed subscription || dfx deploy subscription
upgrade_if_alive subscription "$GAMES/Subscription/target/wasm32-unknown-unknown/release/subscription.wasm"
deployed auction || dfx deploy auction --argument "(opt record {
    sol_rpc = opt principal \"$(dfx canister id sol_rpc)\";
    crown_index = opt principal \"$INDEX_ID\" })"
upgrade_if_alive auction "$GAMES/Auction/target/wasm32-unknown-unknown/release/auction.wasm"

# The relayer is created LAST, after every game, so it lands on a fresh id and
# never shifts the games' ids (their resolvers depend on those ids). It is the
# platform's paid pusher: the page and the smoke runs call its `submit` with an
# ordinary call, and it forwards to crown-index with cycles. Allowlisted to the
# operator (dfx CLI) and the anonymous principal, because the page and smoke use
# an anonymous agent on this local replica; on mainnet the allowlist is the
# platform's authenticated backend instead.
deployed crown-relay || dfx deploy crown-relay --argument "(opt record {
    index = opt principal \"$INDEX_ID\";
    allowlist = opt vec {
        principal \"$(dfx identity get-principal)\"; principal \"2vxsx-fae\" } })"
upgrade_if_alive crown-relay "$RELAY/target/wasm32-unknown-unknown/release/crown_relay.wasm"

for canister in crown-index conditional-tasks conditional-funding auction subscription crown-relay; do
    dfx ledger fabricate-cycles --canister "$canister" --t 100 >/dev/null
done

# The resolver of every live escrow is derived from its game's canister id. If
# an id ever drifts, the escrows born under the old one can only be refunded
# after their deadline — so this is a hard stop, not a warning.
RECORDED=.dfx/local/canister-ids.expected
if [ -f "$RECORDED" ]; then
    drift=0
    while read -r name expected; do
        [ -z "$name" ] && continue
        got=$(dfx canister id "$name" 2>/dev/null || echo "—")
        if [ "$got" != "$expected" ]; then
            echo "FAIL: $name получил id $got, а прежде был $expected" >&2
            drift=1
        fi
    done < "$RECORDED"
    if [ "$drift" = "1" ]; then
        echo "Резолверы игр выводятся из canister id: с новыми id подписи для уже" >&2
        echo "живых эскроу не выдаст никто, деньги достанутся только через refund." >&2
        echo "Останови всё и разберись, прежде чем что-то создавать." >&2
        exit 1
    fi
    echo "== id совпали с прежними: резолверы на месте"
    if ! grep -q "^auction " "$RECORDED"; then
        echo "auction $(dfx canister id auction)" >> "$RECORDED"
        echo "== auction добавлен в $RECORDED"
    fi
else
    for name in sol_rpc crown-index conditional-tasks conditional-funding subscription auction; do
        echo "$name $(dfx canister id "$name")"
    done > "$RECORDED"
    echo "== id записаны в $RECORDED: следующий запуск сверится с ними"
fi

cat > config/local.toml <<EOF
# Generated by scripts/lab-up.sh from the live replica; never committed.
# Everything but the canister ids mirrors config/testnet.toml.
id  = "$(value id)"
rpc = "$SOL_RPC_URL"

splitter = "$SPLITTER"
usdc     = "$USDC"

factory_two_outcome = "$(value factory_two_outcome)"
factory_stream      = "$(value factory_stream)"

fee_bps    = "$(value fee_bps)"
fee_wallet = "$(value fee_wallet)"

ic_host             = "http://127.0.0.1:$(dfx info webserver-port)"
crown_index         = "$INDEX_ID"
crown_relay         = "$(dfx canister id crown-relay)"
conditional_tasks   = "$(dfx canister id conditional-tasks)"
conditional_funding = "$(dfx canister id conditional-funding)"
auction             = "$(dfx canister id auction)"
subscription        = "$(dfx canister id subscription)"
EOF

echo
echo "config/local.toml:"
cat config/local.toml
echo
echo "Резолверы игр греются несколько секунд после первого деплоя."
echo "Дальше: npm run dev  →  открой печатаемый vite URL."
