#!/usr/bin/env bash
# Brings up the lab's replica: one replica for all five canisters, so the
# three games and the book can be driven from one page.
#
# Deliberately WITHOUT --clean. A game canister's resolver is its threshold
# key, and on a local replica that key is derived from the canister id. Wiping
# the replica while escrows are alive on devnet destroys the only key that can
# ever settle or cancel them: the money then waits for refund() and the
# deadline, and nothing else can free it. So this script reuses the replica if
# it is already running, and only deploys what is missing.
#
# Usage: scripts/lab-up.sh            — bring up / top up
#        WIPE=1 scripts/lab-up.sh     — start over (only when no escrow lives)
set -euo pipefail
cd "$(dirname "$0")/.."

SOL_RPC_URL=${SOL_RPC_URL:-https://api.devnet.solana.com}
CORE=${CORE:-$(cd ../Crown-Core && pwd)}
GAMES=${GAMES:-$(cd ../Crown-Games && pwd)}
AR_WASM32=${AR_WASM32:-$HOME/.cache/solana/v1.53/platform-tools/llvm/bin/llvm-ar}

value() { grep "^$1" "config/testnet.toml" | head -1 | cut -d'=' -f2- | tr -d ' "'; }
SPLITTER=$(value splitter)
USDC=$(value usdc)
FACTORIES="$(value factory_two_outcome)\", \"$(value factory_stream)"

echo "== crown-index: local profile (the replica's own sol_rpc has no Default sources)"
SOL_SEED=$(curl -s "$SOL_RPC_URL" -X POST -H "Content-Type: application/json" -d "{
    \"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"getSignaturesForAddress\",
    \"params\":[\"$SPLITTER\", {\"limit\": 1}]}" \
    | python3 -c "import json,sys; print(json.load(sys.stdin)['result'][0]['signature'])")
echo "cursor seed: $SOL_SEED"

cat > "$CORE/config/local.toml" <<EOF
# Generated by Crown-Lab/scripts/lab-up.sh; never committed.
[[chain]]
id        = "solana-devnet"
source    = "Custom:$SOL_RPC_URL"
consensus = "equality"
splitter  = "$SPLITTER"
usdc      = "$USDC"
factories = ["$FACTORIES"]
EOF

echo "== build the wasms"
(cd "$CORE" && CROWN_PROFILE=local \
    CC_wasm32_unknown_unknown="$CORE/scripts/wasm-cc.sh" \
    AR_wasm32_unknown_unknown="$AR_WASM32" \
    cargo build --target wasm32-unknown-unknown --release -p crown-index)
for game in Conditional-Tasks:conditional-tasks Conditional-Funding:conditional-funding Subscription:subscription; do
    dir=${game%%:*}; package=${game##*:}
    (cd "$GAMES/$dir" && cargo build --target wasm32-unknown-unknown --release -p "$package")
done

# The replica must survive this script: never pipe `dfx start --background`
# (the daemon inherits the pipe and the command hangs forever), and never run
# it from a background job whose process group later gets killed.
if ! dfx ping >/dev/null 2>&1; then
    echo "== start the replica"
    [ "${WIPE:-0}" = "1" ] && rm -rf .dfx
    setsid dfx start --background </dev/null >lab-replica.log 2>&1
    for _ in $(seq 1 60); do dfx ping >/dev/null 2>&1 && break; sleep 1; done
    dfx ping >/dev/null 2>&1 || { echo "FAIL: replica never answered"; exit 1; }
else
    echo "== replica already running (resolvers of live escrows preserved)"
fi

deployed() { dfx canister id "$1" >/dev/null 2>&1; }

echo "== canisters"
deployed sol_rpc || dfx deploy sol_rpc
if ! deployed crown-index; then
    dfx deploy crown-index --argument "(opt record {
        sol_rpc = opt principal \"$(dfx canister id sol_rpc)\";
        cursor_seed = opt vec { record { \"solana-devnet\"; \"$SOL_SEED\" } } })"
else
    dfx canister install crown-index --mode upgrade --wasm \
        "$CORE/target/wasm32-unknown-unknown/release/crown_index.wasm" --yes >/dev/null 2>&1 || true
fi
INDEX_ID=$(dfx canister id crown-index)

deployed conditional-tasks || dfx deploy conditional-tasks --argument "(opt record {
    crown_index = opt principal \"$INDEX_ID\" })"
deployed conditional-funding || dfx deploy conditional-funding --argument "(opt record {
    crown_index = opt principal \"$INDEX_ID\" })"
deployed subscription || dfx deploy subscription

for canister in crown-index conditional-tasks conditional-funding subscription; do
    dfx ledger fabricate-cycles --canister "$canister" --t 100 >/dev/null
done

cat > config/local.toml <<EOF
# Generated by scripts/lab-up.sh from the live replica; never committed.
# Everything but the canister ids mirrors config/testnet.toml.
id  = "$(value id)"
rpc = "$SOL_RPC_URL"

splitter = "$SPLITTER"
usdc     = "$USDC"

factory_two_outcome = "$(value factory_two_outcome)"
factory_stream      = "$(value factory_stream)"

fee_bps    = "$(value fee_bps)"
fee_wallet = "$(value fee_wallet)"

ic_host             = "http://127.0.0.1:$(dfx info webserver-port)"
crown_index         = "$INDEX_ID"
conditional_tasks   = "$(dfx canister id conditional-tasks)"
conditional_funding = "$(dfx canister id conditional-funding)"
subscription        = "$(dfx canister id subscription)"
EOF

echo
echo "config/local.toml:"
cat config/local.toml
echo
echo "Резолверы игр греются несколько секунд после первого деплоя."
echo "Дальше: npm run dev  →  открой печатаемый vite URL."
